image: continuumio/miniconda3:latest

stages:
  - preparation
  - test
  - report

preparing_environment:
  stage: preparation

  script:
    - conda env create -f environment.yml
    - source activate som-clustering-knn-imputation

som_test:
  stage: test

  dependencies: preparing_environment

  script:
    - pytest tests/som_test.py

knn_imputation_test:
  stage: test

  dependencies: preparing_environment

  script:
    - pytest tests/knn_imputation_test.py

reporting:
  stage: report

  script:
    - nosetests --with-coverage --cover-erase --cover-package=tests/ --cover-html