image: continuumio/miniconda3:latest

stages:
  - test

before_script:
  - conda env create -f environment.yml
  - source activate som-clustering-knn-imputation

som_test:
  stage: test

  script:
    - pytest tests/som_test.py

knn_imputation_test:
  stage: test

  script:
    - pytest tests/knn_imputation_test.py